/**
 * Bundles the playground web page into a single self-contained HTML document and emits it as a
 * TypeScript module (`playground-page.generated.ts`) exporting the markup as a string. The CLI imports
 * that constant, so the whole page is inlined into the compiled bundle — there is no separate asset to
 * ship, copy, or read at runtime (see `src/playground/data-access/playground-page.ts`).
 *
 * The generated module is committed (like a generated client), so the import resolves for lint, types,
 * tests, and a fresh checkout without a build step. Nothing regenerates it implicitly: run
 * `bun run build:playground` and commit the result whenever the page sources under this directory
 * change. CI regenerates it with the pinned Bun and fails when the committed copy is stale.
 *
 * The script is not minified. The page is served over localhost, so size barely matters, and renamed
 * identifiers would turn every Bun upgrade into a full-file diff of the generated module.
 */
import { join } from 'node:path'

const webRoot = join(import.meta.dir, '..', 'src', 'playground', 'web')
const outFile = join(webRoot, 'playground-page.generated.ts')

const result = await Bun.build({
  // Bun only inlines `process.env.NODE_ENV` in dot form. Replacing the whole object also covers the
  // `process.env["NODE_ENV"]` checks some kit packages use, which would throw in the browser.
  define: { 'process.env': JSON.stringify({ NODE_ENV: 'development' }) },
  entrypoints: [join(webRoot, 'playground-main.ts')],
  format: 'esm',
  minify: false,
  target: 'browser',
})

if (!result.success || result.outputs[0] === undefined) {
  for (const message of result.logs) {
    console.error(message)
  }

  process.exit(1)
}

const script = await result.outputs[0].text()
const style = await Bun.file(join(webRoot, 'playground.css')).text()

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Solana Mobile Playground</title>
<style>
${style}</style>
</head>
<body>
<main id="app"></main>
<script type="module">
${script.replaceAll('</script', '<\\/script')}</script>
</body>
</html>
`

// One string literal per line of HTML, so a change to the page shows up as a readable line diff.
const lines = html
  .split('\n')
  .map((line) => `  ${JSON.stringify(line)},`)
  .join('\n')

const module = `// Generated by \`bun run build:playground\` from the sources in this directory — do not edit.
export const PLAYGROUND_PAGE = [
${lines}
].join('\\n')
`

await Bun.write(outFile, module)

console.log(`Built ${outFile} (${(html.length / 1024).toFixed(0)} kB of HTML)`)
