/**
 * Bundles the playground web page into a single self-contained HTML document and emits it as a
 * TypeScript module (`playground-page.generated.ts`) exporting the markup as a string. The CLI imports
 * that constant, so the whole page is inlined into the compiled bundle — there is no separate asset to
 * ship, copy, or read at runtime (see `src/playground/data-access/playground-page.ts`).
 *
 * The generated module is committed (like a generated client), so the import resolves for lint, types,
 * tests, and a fresh checkout without a build step. `bun run build` regenerates it before bundling, so
 * the published page always matches the current source; run `bun run build:playground` and commit the
 * result whenever the page sources under this directory change.
 */
import { join } from 'node:path'

const webRoot = join(import.meta.dir, '..', 'src', 'playground', 'web')
const outFile = join(webRoot, 'playground-page.generated.ts')

const result = await Bun.build({
  entrypoints: [join(webRoot, 'playground-main.ts')],
  format: 'esm',
  minify: true,
  target: 'browser',
})

if (!result.success || result.outputs[0] === undefined) {
  for (const message of result.logs) {
    console.error(message)
  }

  process.exit(1)
}

const script = await result.outputs[0].text()
const style = await Bun.file(join(webRoot, 'playground.css')).text()

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Solana Mobile Playground</title>
<style>
${style}</style>
</head>
<body>
<main id="app"></main>
<script type="module">
${script.replaceAll('</script', '<\\/script')}</script>
</body>
</html>
`

const module = `// Generated by \`bun run build:playground\` from the sources in this directory — do not edit.
export const PLAYGROUND_PAGE = ${JSON.stringify(html)}
`

await Bun.write(outFile, module)

console.log(`Built ${outFile} (${(html.length / 1024).toFixed(0)} kB of HTML)`)
